<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str; // Import the DB facade
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB; 


class usersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        DB::table('users')->insert([
            [
                'id_user' => 1,
                'nip' => null,
                'nama' => 'Adminum',
                'pangkat' => null,
                'Users_groupId' => 0,
                'username' => 'admin123',
                'password' => Hash::make('Admin123'), // Encrypt the password
                'role' => 'admin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 2,
                'nip' => '197409092003121003',
                'nama' => 'Yunadi',
                'pangkat' => 'IV/c',
                'Users_groupId' => 1,
                'username' => 'yunadi123',
                'password' => Crypt::encryptString('Yunadi123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 3,
                'nip' => '198303302006041004',
                'nama' => 'Muhammad Radhia Wardana',
                'pangkat' => 'IV/b',
                'Users_groupId' => 2,
                'username' => 'wardana123',
                'password' => Crypt::encryptString('Wardana123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 4,
                'nip' => '197503081999032002',
                'nama' => 'Siti Sofia Emalia',
                'pangkat' => 'IV/a',
                'Users_groupId' => 3,
                'username' => 'emalia123',
                'password' => Crypt::encryptString('Emalia123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 5,
                'nip' => '197508072002121003',
                'nama' => 'Agus Salim',
                'pangkat' => 'IV/b',
                'Users_groupId' => 4,
                'username' => 'salim123',
                'password' => Crypt::encryptString('Salim123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 6,
                'nip' => '197110241998032002',
                'nama' => 'Dewi Nurul Mustaqimah',
                'pangkat' => 'III/d',
                'Users_groupId' => 6,
                'username' => 'mustaqimah123',
                'password' => Crypt::encryptString('Mustaqimah123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 7,
                'nip' => '196708211993032008',
                'nama' => 'Yeyen Heryani',
                'pangkat' => 'III/d',
                'Users_groupId' => 7,
                'username' => 'heryani123',
                'password' => Crypt::encryptString('Heryani123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 8,
                'nip' => '197005061998032002',
                'nama' => 'Yayah Nuriyah',
                'pangkat' => 'III/d',
                'Users_groupId' => 8,
                'username' => 'nuriyah123',
                'password' => Crypt::encryptString('Nuriyah123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 9,
                'nip' => '197207041999031005',
                'nama' => 'Yusuf Budi Santoso',
                'pangkat' => 'III/d',
                'Users_groupId' => 9,
                'username' => 'santoso123',
                'password' => Crypt::encryptString('Santoso123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 10,
                'nip' => '198410262009042006',
                'nama' => 'Dewi Hiasri Oktaviani',
                'pangkat' => 'III/d',
                'Users_groupId' => 11,
                'username' => 'oktaviani123',
                'password' => Crypt::encryptString('Oktaviani123'),
                'role' => 'superadmin',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 11,
                'nip' => '196204151992031003',
                'nama' => 'Endang Wawan',
                'pangkat' => 'IV/d',
                'Users_groupId' => 5,
                'username' => 'wawan123',
                'password' => Crypt::encryptString('Wawan123'),
                'role' => 'pegawai',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 12,
                'nip' => '196411211992031003',
                'nama' => 'Kamardi',
                'pangkat' => 'IV/d',
                'Users_groupId' => 5,
                'username' => 'kamardi123',
                'password' => Crypt::encryptString('Kamardi123'),
                'role' => 'pegawai',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 13,
                'nip' => '196512141992032001',
                'nama' => 'Euis Nurkhaeroni',
                'pangkat' => 'IV/d',
                'Users_groupId' => 5,
                'username' => 'nurkhaeroni123',
                'password' => Crypt::encryptString('Nurkhaeroni123'),
                'role' => 'pegawai',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 14,
                'nip' => '196805071993031007',
                'nama' => 'Abd Azis',
                'pangkat' => 'IV/d',
                'Users_groupId' => 5,
                'username' => 'azis123',
                'password' => Crypt::encryptString('Aziss123'),
                'role' => 'pegawai',
                'photo' => null,
                'remember_token' => null, //Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
